[package]
name = "chatot"
version = "0.1.0"
edition = "2024"
description = "A text archive decoder and encoder for the generation IV Pok√©mon games"

[dependencies]
clap = { version="4.5.53", features= ["derive"] }
